### ISSUE TITLE
Hello world - Python

### ISSUE THREAD

**Issue by joepreludian** [roquitski/Hello-world#3]
Você precisa iniciar um projeto em Django. =)
Ele será apenas o hello world que já vem nele próprio. Quero que você aprenda agora como instalar um projeto no django, rodá-lo e versioná-lo no git.

Notas: 
* Você precisa instalar o djando através do "pipenv".
* Quero apenas o projeto inicial rodando;
* Quero que você leia sobre gitignore. Existem arquivos que não precisam ser versionados.
  * Existe um site muito bom chamado "gitignore.io"; Dá uma olhada.

Beijo. Boa sorte. Qualquer dúvida responda nessa thread.

**Comment by roquitski** [comment]
Hey  @joepreludian ,  estou com um problema eu consegui fazer o push dos arquivos do projeto em Django porque eu forcei, porém ele sobrescreveu os outros arquivos.
Se eu tento de novo ele dá o seguinte erro. Pode me ajudar?

[gabi@localhost Hello-world]$ git push -u origin master
Username for 'https://github.com': roquitski
Password for 'https://roquitski@github.com': 
To https://github.com/roquitski/Hello-world.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/roquitski/Hello-world.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by joepreludian** [comment]
Certo. Você antes precisa dar um git pull antes do push. :)

Não é uma boa pratica forçar o git. Logo vc precisa antes "sincronizar o
repositório local com o remoto" antes de realizar um git push.

Veja a documentação do git pull.

**Comment by roquitski** [comment]
First Hello-word in python/django
Git is working appropriately.
